### ISSUE TITLE
NavigationControl

### ISSUE THREAD

**Issue by matis-dk** [urbica/react-map-gl#116]
**Is your feature request related to a problem? Please describe.**
I miss a NavigationControl component, just like Uber's implementation.
https://uber.github.io/react-map-gl/#/Documentation/api-reference/navigation-control

**Describe the solution you'd like**
The API could be completely identical to Uber's solution

**Additional context**
Some users have a harder time navigating a map, so adding navigation buttons would definitely help.

**Comment by stepankuzmin** [comment]
Hi @matis-dk! Thanks for the issue!

I've added `mapbox-gl` controls as a separate components (AttributionControl, FullscreenControl, GeolocateControl, NavigationControl, ScaleControl) in [0.7.0-beta.0](https://github.com/urbica/react-map-gl/releases/tag/v0.7.0-beta.0). 

I want to keep the project as simple as possible, so we don't plan to use the same API as Uber's solution as it would require a lot of rewriting and refactoring current codebase.

I've exposed `MapContext` in the latest release, so you can use it to build your own NavigationControl that will have an access to the `map` instance.

```jsx
import { MapContext } from '@urbica/react-map-gl';

<MapContext.Consumer>
  {map => /* render something based on the map instance */}
</MapContext.Consumer>
```

You can go through the current implementation of [NavigationControl](https://github.com/urbica/react-map-gl/blob/master/src/components/NavigationControl/index.js) for example.
