### ISSUE TITLE
Add MapboxLanguage control

### ISSUE THREAD

**Issue by Tuizi** [urbica/react-map-gl#167]
**Is your feature request related to a problem? Please describe.**
Yes, we would like to display mapbox in multiple language
https://github.com/mapbox/mapbox-gl-language

**Describe the solution you'd like**
We should be able to add it like any other control: https://urbica.github.io/react-map-gl/#/Controls

**Describe alternatives you've considered**
An alternative solution would be to use directly the `map` instance and to add it manually, but I really love the composition approach of Urbica's MapGL

**Additional context**
I would be more than happy to create the pull request for that

**Comment by stepankuzmin** [comment]
Hi @Tuizi! I'm glad you liked MapGL!

We do accept pull requests, so if you are interested, I can help you with that. We can ship it with the next release.

**Comment by stepankuzmin** [comment]
Awesome job, @Tuizi! Published as [v1.3.0](https://github.com/urbica/react-map-gl/releases/tag/v1.3.0).
