### ISSUE TITLE
Bug? Dynamic sources and layers 

### ISSUE THREAD

**Issue by lapidus** [urbica/react-map-gl#195]
I am rendering a dynamic list of Sources and Layers:

```
// inside react render ... 

{ sources.map(s => (
    <Source [some props] />
))}
{sources.map(s => (
     <Layer [some props] />
))}
```

This works well on load but when I subsequently filter sources, I get this type of error:

> Source "primary" cannot be removed while layer "primary" is using it

![image](https://user-images.githubusercontent.com/66601/56082827-e628b200-5e1d-11e9-8386-c6c2ec6f6483.png)

It seems the mapbox operation under the hood is asynchronous so that I cannot delete a source in the same render as I delete a layer. How can I work around this? Or could you possibly build in some safeguards against this behaviour?

Thanks!

**Comment by stepankuzmin** [comment]
Hi @lapidus! Thanks for the issue!

What version do you use? Could you please provide a reproducible example?

**Comment by lapidus** [comment]
Hi!

It seems they had the same issue here:
https://github.com/alex3165/react-mapbox-gl/issues/493

And resolved by removing layers before sources:
https://github.com/alex3165/react-mapbox-gl/commit/986b555599ee704de888ac9f5086504b1ff6babe

**Comment by lapidus** [comment]
I could try to do a PR later, any hints appreciated :)

**Comment by lapidus** [comment]
Gah, gosh! I just realized you fixed this 6 days ago:
https://github.com/urbica/react-map-gl/commit/3f228af65660dab00ffa98b79c51abe5180dcfc2#diff-c4273adc64deb9bc0ebb2446633a17cd

I was still on version 1.3. Sorry about that and thank you for a great lib!

**Comment by stepankuzmin** [comment]
No problem, glad to hear that this worked for you :)
