### ISSUE TITLE
Possibility to update my deck.gl custom layer

### ISSUE THREAD

**Issue by sameerchandra** [urbica/react-map-gl#203]
Is it possible to update my deck.gl custom layer?

**Comment by stepankuzmin** [comment]
Hi @sameerchandra! What do you mean?

**Comment by sameerchandra** [comment]
Is it possible to update my deck.gl custom layer dynamically?

**Comment by stepankuzmin** [comment]
Oh, I see. You can utilize deck.gl [`setProps`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/mapbox/mapbox-layer.md#setpropsprops) method on layer instance for dynamic updates. There is no general way to dynamically update `CustomLayer` as there may be different implementations. However, we may add some kind of dynamic props support in the future releases.
