### ISSUE TITLE
Browser default language for LanguageControl

### ISSUE THREAD

**Issue by ankitshah2193** [urbica/react-map-gl#232]
Hello,

Is there any way we can pass browser language as a default language to language control? 

Can we also display two languages like English and Local language for labels like it's in google maps?

**Comment by stepankuzmin** [comment]
Hi!

Yes, you can pass [preferred language of the user](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language) as a `language` prop into `LanguageControl`.

You can also design your custom map style with [Mapbox Studio](https://www.mapbox.com/mapbox-studio/) and pass it as a `mapStyle` prop into `MapGL` component.
