### ISSUE TITLE
Allow mapbox-gl >= 1.0

### ISSUE THREAD

**Issue by znewton** [urbica/react-map-gl#243]
**Is your feature request related to a problem? Please describe.**
My team is using this project, but would like to use mapbox's newest pricing model which is activates when using mapbox-gl v1.0 because it supports better deals at volume.

>Volume discounts for all: Discounts increase as usage grows, when an application reaches volume scale, it automatically gets volume pricing. With progressive discounts, we’re smoothing out the pricing curve so a developer using 999,999 API calls doesn’t pay more than someone using 1,000,000 API calls. No negotiation necessary.
> - [Mapbox New Pricing Blog Post](https://blog.mapbox.com/new-pricing-46b7c26166e7)

**Describe the solution you'd like**
Ideally, the mapbox-gl peer dependency would not restrict to a version lower than 1.0. Instead, changing the peerDependency to be `<=1.0.0` would allow for updating to the new pricing model with no breaking code changes.

**Describe alternatives you've considered**
Bumping our mapbox-gl version lock to1.0 and ignoring the peerDependency warning.

**Additional context**
[Mapbox GL 1.0.0 Pricing model release](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#100)

**Comment by stepankuzmin** [comment]
Fixed in the latest `1.11.0` version.
