### ISSUE TITLE
No layers displayed when switching to a different mapStyle

### ISSUE THREAD

**Issue by anatolysukhanov** [urbica/react-map-gl#255]
**Describe the bug**
Layers are not rendered when mapStyle is changed dynamically.

**To Reproduce**
1. Go to https://codesandbox.io/s/purple-leaf-4u70x
2. Click on 'Change Style'

**Expected behavior**
A change in the map style should preserve layers on the map (like in the "switch-style" demo on http://alex3165.github.io/react-mapbox-gl/demos).

**Screenshots**

![image](https://user-images.githubusercontent.com/7021042/64807699-6f473f00-d59e-11e9-8b5f-38ef746ec237.png)

**Desktop:**
 - Browser [Firefox, Chrome]

**Comment by stepankuzmin** [comment]
Fixed temporary in `v1.11.2` until https://github.com/mapbox/mapbox-gl-js/issues/8691 resolves

**Comment by sabres207** [comment]
this still happens to me using version 7.0.17.
