### ISSUE TITLE
Event handlers are not removed when a Layer is unmounted

### ISSUE THREAD

**Issue by warborn** [urbica/react-map-gl#258]
**Describe the bug**
Currently there is an issue in which the Layer component doesn't remove all of the event handlers associated with it, therefore when you unmount and mount again the same Layer component, the event handlers will be declared again and will be called more than once per event type.

**To Reproduce**
1. Create a Layer component that can be rendered conditionally (for example, based on a toggle button)
2. Declare an `onClick` handler for the layer that print on the console that the layer has been clicked
3. Toggle on and off the layer by using the button
4. See how the click handler fires the same number of times the Layer has been mounted

**Expected behavior**
The event handlers for the layer must be removed when the component has been unmounted

**Additional context**

**Comment by stepankuzmin** [comment]
Thanks for contributing, @warborn! Released as v1.12.1
