### ISSUE TITLE
Paint Layer depending on layer properties

### ISSUE THREAD

**Issue by rendomnet** [urbica/react-map-gl#268]
Can we paint layer using it properties.
For example i'm storing size and color in geojson.

```
{
 type: "FeatureCollection",
 type: "Feature",
 features: [{
              geometry: {
                type: "Point",
                coordinates: [-12, 2]
              },
              properties: {
                color: 'green',
                type: 4
              }
}]
}


<Layer
            id="other"
            type="circle"
            source="parks"
            paint={
                "circle-radius": properties.type > 3 ? 6 : 2,  <--- something like this?
                "circle-color":  properties.color, <--- and this
                "circle-opacity": 1
              };
            }}
          />
```

**Comment by device25** [comment]
Hi @rendomnet yes you can do it.
You should use expressions for this, check [expressions doc](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-match), [data-driven-lines example](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-lines/) and [data-driven-circle-colors example](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/)
