### ISSUE TITLE
Highlight feature on click

### ISSUE THREAD

**Issue by rendomnet** [urbica/react-map-gl#269]
How to highlight specific `Feature` when you click on it. For example I have circle `Feature` and when I'm clicking on one specific circle I want to make it bigger and change color or even change type of this marker to `symbol` with image.

**Comment by device25** [comment]
You can use [FeatureState Component](https://urbica.github.io/react-map-gl/#/Components/FeatureState) to implement this behavior

**Comment by device25** [comment]
Hi @rendomnet 
Did FeatureState help you?

**Comment by rendomnet** [comment]
@device25 yeah. Thank you
