### ISSUE TITLE
transition viewport

### ISSUE THREAD

**Issue by benamm** [urbica/react-map-gl#278]
hi...
how can i use FlyToInterpolator @urbica/react-map-gl

**Comment by stepankuzmin** [comment]
`@urbica/react-map-gl` doesn't have `transitionInterpolator`, you have to use `viewportChangeMethod` and `viewportChangeOptions` for this

See `Viewport Change Methods` section in https://urbica.github.io/react-map-gl/#/Components/MapGL
also https://docs.mapbox.com/mapbox-gl-js/api/#animationoptions
