### ISSUE TITLE
Add support for full list of options provided by MapboxGL

### ISSUE THREAD

**Issue by amytych** [urbica/react-map-gl#279]
**Is your feature request related to a problem? Please describe.**
Let me start with saying that Urbica is great to work with, thank you for the excellent work! 👍 

I've tried to use some of the options supported by Mapbox GL and was caught off guard to see them not having any effect. Specifically I wanted to tweak `fadeDuration` and disable `crossSourceCollision`, as documented in [Mapbox GL API reference](https://docs.mapbox.com/mapbox-gl-js/api/#map).

Seeing that it didn't work I peeked at the Urbica source for `MapGL` component and it looks like the list of props passed to `mapboxgl.Map` constructor is restricted to a fixed subset.

https://github.com/urbica/react-map-gl/blob/c2effc259910bfa5b86a578cafda53e2075e57d6/src/components/MapGL/index.js#L310-L342

**Describe the solution you'd like**
I'd like to be able to pass all options supported by Mapbox GL API. Extracting the props specific to Urbica MapGL or which need to be manipulated in any way (which should not be passed to `mapboxgl.Map` constructor directly) and spreading the rest of the props in the `mapboxgl.Map` constructor (though this risks creating confusion with the other options being passed directly via individual props)?

**Describe alternatives you've considered**
Expanding the list of options by adding individual items, following the current approach (not sure how scalable it is though)? Or maybe adding an `additionalMapOptions` prop (or similarly named) that could be spread as is in the `mapboxgl.Map` constructor?

**Additional context**
If it's for some reason not possible to match the Urbica MapGL props to the options that Mapbox GL supports, it would be good to provide a clear information about in the docs. It's not obvious right now that it's only a subset.

**Comment by stepankuzmin** [comment]
Hey @amytych! Thanks for filling the issue for that. I've released [v1.13.0](https://github.com/urbica/react-map-gl/releases/tag/v1.13.0) that add `fadeDuration`, `crossSourceCollisions`, and `locale` props

**Comment by amytych** [comment]
Thanks for such a quick response and the fix @stepankuzmin!

Just a note, it still might be valuable to either support all Mapbox GL options or point out in the docs that only a subset is supported to avoid any confusions others might experience like I did.

Thanks again! 👍
