### ISSUE TITLE
Map click is fired before marker clicks

### ISSUE THREAD

**Issue by derwaldgeist** [urbica/react-map-gl#283]
I want to:
- create markers by clicking on the map
- open info about a marker by clicking on the marker

I can do this by adding onClick handlers to the map and the markers, respectively.

However, if I click on a marker, the map's onClick handler is always fired first, and the marker's onClick handler is being fired second. This is counterintuitive, because you cannot prevent clicks from being propagated from the marker to the (underlying) map in this scenario. Which basically kills this use-case.

I would expect that the markers' onClick handlers would be fired first, because they appear "closer" to the user.

**Comment by derwaldgeist** [comment]
Hi, is there any chance to get this fixed soon? Our usability suffers from this, because it actually prevents us from implementing a "tap on map" feature.

**Comment by derwaldgeist** [comment]
Shameless Bump :-)

**Comment by stepankuzmin** [comment]
Hey @derwaldgeist!

Sorry for the delay. I've added separate `onClick` handler for `<Marker/>` component which is fired before `<Map/>` `onClick`. There is also a new [example](https://urbica.github.io/react-map-gl/#/Components/Marker) in docs for this case.

Released as [v1.14.0](https://github.com/urbica/react-map-gl/releases/tag/v1.14.0)

**Comment by derwaldgeist** [comment]
Hi @stepankuzmin I tried this out with 1.14.1, but still the map's `onClick` is being fired before the marker's `onClick`. What may I be doing wrong?

**Comment by derwaldgeist** [comment]
Sorry, my bad. I had built my own wrapper for <Marker> to allow for onClick. With the new directly supported onClick, it's working fine. Thanks again for implementing this!
