### ISSUE TITLE
Add Typescript type definitions

### ISSUE THREAD

**Issue by dellisd** [urbica/react-map-gl#290]
**Is your feature request related to a problem? Please describe.**
It currently isn't possible to use this package with Typescript without enabling "implicit any" or defining types for each of the components and props that are used.

**Describe the solution you'd like**
A `.d.ts` file published with the library, or otherwise published through definitely typed.

**Describe alternatives you've considered**
It's possible to manually define the types using module enhancement, but this is a lot of work for each project when it could be packaged with the library.

**Additional context**

**Comment by maxnowack** [comment]
Since #357 was merged, this issue can be closed, right? 🙂

**Comment by maxnowack** [comment]
Ah, it seems that this is not yet published to npm

**Comment by stepankuzmin** [comment]
Thanks all! It's published now, closing the issue
