### ISSUE TITLE
'isBrowser' check in utils/mapbox-gl prevents rendering in Electron

### ISSUE THREAD

**Issue by WesWedding** [urbica/react-map-gl#307]
**Describe the bug**
Code intended to detect Server Side Rendering gets triggered in Electron when an Electron app has been bundled as a Mac or Windows application because `global.process` exists.  Potentially other "browser-like" environments do this, as well.  This results in MapGL components being non-functional, even in environments that should normally be able to render mapbox.

The "isBrowser" in `utils/mapbox-gl.js` is the culprit.

In addition to issues with code that might rely on a function ref to a MapGL component, the internals of MapGL also throw errors when componentDidUpdate() triggers.

**To Reproduce**
1. Create a basic Electron app (grab a quickstart)
2. Create a basic react-map-gl (I do not have an example yet)
3. Tell the Electron app to load the example (ie. https://localhost:3000)

**Expected behavior**
The map should render in any Electron as would in any other browser.  MapboxGL is fully supported.

**Comment by WesWedding** [comment]
While creating a repo for an easy test/example I've realized that this issue is a little more obtuse than I thought.  It looks like this issue is specifically when Electron is turned into an app via Electron Builder; in Electron Builder the global.process variable exists.

**Comment by stepankuzmin** [comment]
Hi @WesWedding 👋

This should work now with the latest release [v1.16.1](https://github.com/urbica/react-map-gl/releases/tag/v1.16.1)
