### ISSUE TITLE
[Question] Code and Link for the examples in the README

### ISSUE THREAD

**Issue by cedricdelpoux** [urbica/react-map-gl#309]
Hello, 

I would like to achieve the following result in the README with a scale of colors for popular routes but I can't find a demo link.

<img width="396" alt="Screenshot 2020-11-15 at 15 38 10" src="https://user-images.githubusercontent.com/2683300/99187757-b14ab280-2758-11eb-8b33-100f0e473fa3.png">

Where can I find the code please?
Thank you

**Comment by stepankuzmin** [comment]
Hi @cedricdelpoux! Unfortunately this example is not currently maintained, bu you can [find it here](https://urbica.github.io/bikes/) under "Fares". Source code is also available at https://github.com/urbica/bikes
