### ISSUE TITLE
Missing API token in Docs breaks all examples

### ISSUE THREAD

**Issue by gabeamaleoni** [urbica/react-map-gl#310]
**Describe the bug**
Each of the examples in the docs has a broken map because of a missing or dated API token

**To Reproduce**

1. Go to https://urbica.github.io/react-map-gl/#/Components/Source

**Expected behavior**
A map would appear with the example code from below

**Screenshots**

![image](https://user-images.githubusercontent.com/8764019/99849270-1d019680-2b30-11eb-919f-2ebba40c9a4e.png)

**Comment by stepankuzmin** [comment]
Hi, @gabeamaleoni, thanks so much for noticing this, fixed https://urbica.github.io/react-map-gl/#/Components/Source
