### ISSUE TITLE
Map Component's onClick props do not update

### ISSUE THREAD

**Issue by SebastianCJ** [urbica/react-map-gl#324]
**Describe the bug**
When using the onClick function of the map component props dont get updated and instead remain with the first initial value when the component mounts. This only happens inside the onClick function.

**To Reproduce**
1. Setup the map
2. add onClick function
3. P

**Expected behavior**
I expect that props inside the onClick function get the current value its getting from its parent

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 90.0.4430.85 (Official Build) (x86_64)

**Additional context**
https://codesandbox.io/s/886nn
Made a simple sandbox showing the error

**Comment by wrdaigle** [comment]
You need to memoize the onClick callback so it updates each time `canSet` updates.
```  
  const onClick = useCallback(
    (event) => {
      console.log("EVENT: ", event);
      console.log("canSet click: ", canSet);
    },
    [canSet]
  );
```
Also, if you want to pass the state value to a sub component, you will need to pass include the value (just including the name will always return `true`.

```
<Map canSet={canSet} />
```

**Comment by SebastianCJ** [comment]
I've updated the codesandbox with the useCallback but am getting the same behavior.

**Comment by wrdaigle** [comment]
Hmm. I'm not sure why that wasn't working.  Here is a slightly more convoluted code sample that has the desired effect. 

https://codesandbox.io/s/thirsty-nash-2hzrm?file=/src/Map.js
