### ISSUE TITLE
Replace 'require' statement with 'import'

### ISSUE THREAD

**Issue by KaiHuebner** [urbica/react-map-gl#330]
Deploying my project in [vite](https://vitejs.dev/) fails because of a `require` statement.
Please replace it with an `import` statement.

[src/utils/mapbox-gl.js](https://github.com/urbica/react-map-gl/blob/d06434d979f99dac8c0140fedd43458b9854102a/src/utils/mapbox-gl.js)
```
9  | // $FlowFixMe
10 | const mapboxgl: MapboxGL = isBrowser ? require('mapbox-gl') : null;
11 |
12 | export default mapboxgl;
```

to something like this

```
9  | // $FlowFixMe
10 | const mapboxgl: MapboxGL = null;
11 | if (isBrowser) import mapboxgl from 'mapbox-gl'
12 | export default mapboxgl;
```

**Comment by Digital-Coder** [comment]
@KaiHuebner did you find a workaround ?

**Comment by stepankuzmin** [comment]
Hi @KaiHuebner 👋 

This should work now with the latest release [v1.16.1](https://github.com/urbica/react-map-gl/releases/tag/v1.16.1)
