### ISSUE TITLE
Incompatibility with Vitejs

### ISSUE THREAD

**Issue by Digital-Coder** [urbica/react-map-gl#371]
**Describe the bug**
Hi @stepankuzmin! I have been migrating open source  `create-react-app@4.0.3` application to  [Vitejs](https://vitejs.dev/), but this package has some problems. By adding  `@urbica/react-map-gl` , in the browser console I get errors like : `global is not defined` and if I find hacky way to add global then I get error that ` require is not defined`. I think this package is  not compatible with `create-react-app@5.0.0 (webpack 5)` too because it does not ship with nodejs polyfills anymore.

It seems that these issues are caused by isBrowser function and require() commonJs import here [src/utils/mapbox-gl.js](https://github.com/urbica/react-map-gl/blob/d06434d979f99dac8c0140fedd43458b9854102a/src/utils/mapbox-gl.js) and one of the users has responded by potential fix here : #330.
I would really appreciate if you could look into this, 

**To Reproduce**
You could check this playground here  with [Vite](https://stackblitz.com/edit/vitejs-vite-x8aavq?file=src/App.jsx)
`npm run dev `in the terminal
and open browser console

or 
 npm create vite@latest
 npm i mapbox-gl @urbica/react-map-gl
add map to the app.jsx
check browser console

**Expected behavior**
Compatability with webpack v4,v5, and Vite which uses rollup bundler

**Comment by Digital-Coder** [comment]
maybe this issue is related too #314 ?

**Comment by stepankuzmin** [comment]
Hey @Digital-Coder 👋

Thanks for sharing, this may be related

**Comment by Digital-Coder** [comment]
@stepankuzmin I forgot to update ! I was able to make it work for vitejs by changing [src/utils/mapbox-gl.js](https://github.com/urbica/react-map-gl/blob/d06434d979f99dac8c0140fedd43458b9854102a/src/utils/mapbox-gl.js) to something like this:
```
import map from 'mapbox-gl';

const isBrowser =
  typeof window !== 'undefined' && typeof window.document !== 'undefined';

let mapboxgl = null;
mapboxgl = isBrowser ? (mapboxgl = map) : null;
export default mapboxgl;
```

For `create-react-app@5.0 `I had to add /* eslint-disable */ to react-map-gl.esm.js file and  change browser list in `package.json `to this for proper transpilation. [https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling](url)
   ```
 "browserslist": {
      "production": [
       "defaults",
        "not ie 11"
      ],
      "development": [
        "last 1 chrome version",
        "last 1 firefox version",
        "last 1 safari version"
      ]
    }
```
I am not opening PR because I saw in your codebase you are using types so this solution might need some tweaks, but hopefully its very helpful

**Comment by stepankuzmin** [comment]
Hi @Digital-Coder 👋 

This should work now with the latest release [v1.16.1](https://github.com/urbica/react-map-gl/releases/tag/v1.16.1)

**Comment by Digital-Coder** [comment]
> Hi @Digital-Coder 👋
> 
> This should work now with the latest release [v1.16.1](https://github.com/urbica/react-map-gl/releases/tag/v1.16.1)

seems to be working, thank you !
