### ISSUE TITLE
Wrong typing for <Marker> component

### ISSUE THREAD

**Issue by azuken** [urbica/react-map-gl#373]
**Describe the bug**
Since latest version (1.15.0), onClick type definition is `() => any`, instead of `(e: Event) => void`. This leads to typescript error when trying to use event parameter.

**To Reproduce**
```tsx
      <Marker
        onClick={
          (e => {
            e.preventDefault();
            e.stopPropagation();
          }) as () => any // Workaround for wrong typing
        } />
```
**Expected behavior**
True typing

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 99.0.4844.83

**Comment by alexbidule** [comment]
+1
