### ISSUE TITLE
Cleaning up old cluster components in the virtual DOM tree

### ISSUE THREAD

**Issue by matis-dk** [urbica/react-map-gl#93]
### Issue
It looks like MapGL isn't cleaning up old cluster components in the virtual DOM tree

### How to replicate
Zoom into a cluster until it expand and inspect the virtual tree
Then zoom out to the previous zoom level
The following will lead into duplicated / identical cluster components with the same id

### Potential solution
Reuse or clean up old clusters

**Comment by stepankuzmin** [comment]
Hi @matis-dk! Thanks for the issue.

It seems that there is cluster ids overlapping then we recreate clusters with the new children. This also affects https://github.com/urbica/react-map-gl/issues/94. See https://github.com/mapbox/supercluster/issues/97 for more info.

Meanwhile I'll dig into some workaround here.

**Comment by stepankuzmin** [comment]
Fixed in https://github.com/urbica/react-map-gl/commit/d57852adf85cfbd117da23b637f452ab486789f3. Try to update `@urbica/react-map-gl` to `0.6.0-beta.16` version
